import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("-----------------------------")
print("Load & Clean Data")
print("-----------------------------")
file_path = r"C:\Users\Muttaki\Desktop\analysis gov\data-resource_2024_06_24_Table-15 Deposits Amount Distributed by Types of Account.csv"
raw = pd.read_csv(file_path)

print(" Extract header (row 1 = deposit types")
deposit_types = raw.iloc[1].tolist()
deposit_types[0] = "Quarter"
df = raw.iloc[2:].copy()
df.columns = deposit_types

print("Drop NaN columns")
df = df.dropna(axis=1, how="all")

print("Convert numeric columns")
for col in df.columns[1:]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("-----------------------------")
print("Parse Year and Quarter safely")
print("-----------------------------")
df["Year"] = df["Quarter"].astype(str).str.extract(r"(\d{4})")[0]
df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
df["Q"] = df["Quarter"].astype(str).str.extract(r"(Q-\d)")[0]

print("-----------------------------")
print("Clean Quarter Column for Plotting")
print("-----------------------------")
print("Keep only rows with proper YYYY, Q-n format")
df = df[df["Quarter"].str.match(r"\d{4}, Q-\d", na=False)].copy()

print("Order quarters chronologically")
quarters_ordered = sorted(df["Quarter"].unique())
df["Quarter"] = pd.Categorical(df["Quarter"], categories=quarters_ordered, ordered=True)

print("-----------------------------")
print("Dataset Overview / Counter")
print("-----------------------------")
print("----- DATASET OVERVIEW -----")
print(f"Total Rows: {df.shape[0]}")
print(f"Total Columns: {df.shape[1]}")
print(f"Available Years: {df['Year'].nunique()} ({df['Year'].min()} - {df['Year'].max()})")
print(f"Total Quarters: {df['Q'].nunique()}")
print(f"Deposit Types: {df.shape[1] - 3}")
print("\nSample Data:")
print(df.head(5))
print("\nSummary Statistics:")
print(df.describe().T)
print("-----------------------------")
print("Basic Graphs")
print("-----------------------------")
print("Total deposits by Year (bar)")
plt.figure(figsize=(8,5))
df.groupby("Year")["Total Deposits Amount"].sum().plot(kind="bar", color="skyblue")
plt.title("Total Deposits by Year")
plt.ylabel("Crore Tk")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
print("Boxplot for Total Deposits")
plt.figure(figsize=(6,4))
sns.boxplot(y=df["Total Deposits Amount"], color="lightgreen")
plt.title("Boxplot of Total Deposits")
plt.show()
print("Histogram of Total Deposits")
plt.figure(figsize=(8,5))
sns.histplot(df["Total Deposits Amount"], bins=20, kde=True, color="orange")
plt.title("Distribution of Total Deposits")
plt.xlabel("Deposits (Crore Tk)")
plt.ylabel("Frequency")
plt.show()
print(" -----------------------------")
print("Additional Analysis Methods")
print("-----------------------------")
print(" Year-over-Year Growth (%)")
df_yearly = df.groupby("Year")["Total Deposits Amount"].sum().reset_index()
df_yearly["YoY Growth (%)"] = df_yearly["Total Deposits Amount"].pct_change() * 100
print("\nYear-over-Year Growth:")
print(df_yearly)
plt.figure(figsize=(8,5))
sns.lineplot(data=df_yearly, x="Year", y="YoY Growth (%)", marker="o")
plt.title("Year-over-Year Growth of Total Deposits")
plt.ylabel("Growth (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
print(" Quarterly Trend Analysis (fixed)")
plt.figure(figsize=(12,5))
sns.lineplot(data=df, x="Quarter", y="Total Deposits Amount", marker="o")
plt.title("Quarterly Deposits Trend")
plt.xticks(rotation=90)
plt.ylabel("Crore Tk")
plt.tight_layout()
plt.show()
print("Top 99999 Deposit Types by Total Amount")
deposit_columns = df.columns.difference(["Quarter", "Year", "Q"])
total_by_type = df[deposit_columns].sum().sort_values(ascending=False)
print("\nTop 5 Deposit Types by Total Amount:")
print(total_by_type.head(99999))
plt.figure(figsize=(8,5))
total_by_type.head(99999).plot(kind="bar", color="purple")
plt.title("Top 5 Deposit Types by Total Amount")
plt.ylabel("Crore Tk")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
print("Correlation Heatmap among Deposit Types")
plt.figure(figsize=(12,8))
sns.heatmap(df[deposit_columns].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation between Deposit Types")
plt.show()
print("Quarterly Distribution Boxplots by Deposit Type")
plt.figure(figsize=(12,6))
sns.boxplot(data=df[deposit_columns])
plt.xticks(rotation=45)
plt.title("Boxplot Distribution of Deposit Types")
plt.show()
print("Cumulative Deposit Growth")
df_cum = df.groupby("Year")["Total Deposits Amount"].sum().cumsum()
plt.figure(figsize=(8,5))
df_cum.plot(marker="o", color="darkblue")
plt.title("Cumulative Total Deposits Over Years")
plt.ylabel("Crore Tk")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
